---
title: "Lift_Chart_ROC_Curve"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

## GitHub Documents

R Packages regarding binary lift chart hasn't function well for me.
I'm writing one lift chart and ROC curve for my own convience

## Lift Chart

Read the example dataset
 
```{r cars}
dat<-read.csv("example.csv")
head(dat,5)
```

sort by the order
```{r}
dat<-dat[order(-dat$Propensity),]
for (i in 1:nrow(dat)) {
  dat$accum[i]<-sum(dat$Actual.Class[1:i])  
}
positive<-dat[dat$Actual.Class==1,]
negative<-dat[dat$Actual.Class==0,]
perfect<-c(1:nrow(positive),rep(nrow(positive),nrow(negative)))
worst<-c(rep(0,nrow(negative)),1:nrow(positive))
plt<-data.frame(dat$accum,perfect,worst)
#lift chart
G1<-ggplot(data = plt,aes(y=dat$accum,x=1:1000))+geom_point(shape = ".",colour = 'black')+geom_point(aes(y=plt$perfect,x=1:1000), shape = ".",colour = 'red')+geom_point(aes(y=plt$worst,x=1:1000), shape = ".",colour = 'green')+labs(x="number of observations",y="number of positive occurance")
#need to know the exact loss function
loss<-(perfect-plt$dat.accum)/perfect
mean((perfect-plt$dat.accum)/perfect)
G1+ggtitle("lost percentage is ",round(mean((perfect-plt$dat.accum)/perfect),3))
```


## ROC curve

Write my own ROC function to calculate TPR and FRR for certain cutoff value
```{r pressure, echo=FALSE}
# make new variables
dat$prediction<- -1
#define my function
myfunc<-function(cutoff){
  #not necessary to use for loops and ifelse
  #matrix manipulation is alwats clear and faster
  #make prediction based on cutoff
  dat[dat$Propensity>cutoff,]$prediction<-1
  dat[dat$Propensity<=cutoff,]$prediction<-0
  #proportion of actual positives that are correctly identified
  TPR<-nrow(dat[dat$Actual.Class==1&dat$prediction==1,])/nrow(dat[dat$Actual.Class==1,])
  #proportion of actual negatives that are correctly identified
  FRR<-nrow(dat[dat$Actual.Class==0&dat$prediction==1,])/nrow(dat[dat$Actual.Class==0,])
  return(data.frame(cutoff,TPR,FRR))
}
```

Loop cutoff value to get the whole ROC curve

```{r}
#return ROC
ROC<-data.frame(cutoff=0,TPR=0,FRR=0)
#
for (i in seq(0.01,0.99,0.01)) {
  ROC<-rbind(ROC,myfunc(i))
}
ROC<-rbind(ROC,data.frame(cutoff=1,TPR=1,FRR=1))
head(ROC,5)
```
```{r}
G2<-ggplot(data=ROC,aes(x=ROC$FRR,y=ROC$TPR))
G2+geom_line()+ggtitle("AOC is",round(mean(ROC$TPR),3))
```

